#!/usr/bin/env python3
"""
Generate Dicemaster/test_video.h — a C byte-array embedding a short H.264
Annex-B video of the rotating U-M logo (240×240, 24 fps, looping 3×).

Requires: ffmpeg in PATH, Pillow (python3 -m pip install Pillow)

Usage:
    python3 scripts/gen_test_video.py

Output:
    Dicemaster/test_video.h
"""

import subprocess
import sys
import tempfile
import os
from pathlib import Path

REPO_ROOT    = Path(__file__).resolve().parent.parent
FRAMES_DIR   = REPO_ROOT / "test_images" / "revolving_umlogo"
OUTPUT_H     = REPO_ROOT / "Dicemaster" / "test_video.h"
WIDTH        = 240
HEIGHT       = 240
FPS          = 24
LOOPS        = 3   # repeat the 24-frame sequence N times for a longer clip

def main():
    frames = sorted(FRAMES_DIR.glob("rev_*.jpg"))
    if not frames:
        print(f"ERROR: no frames found in {FRAMES_DIR}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(frames)} frames in {FRAMES_DIR}")

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)

        # Write a concat list that repeats the frames LOOPS times.
        concat_txt = tmp / "frames.txt"
        with open(concat_txt, "w") as f:
            for _ in range(LOOPS):
                for frame in frames:
                    f.write(f"file '{frame}'\n")
                    f.write(f"duration {1/FPS:.6f}\n")
            # ffmpeg concat demuxer needs the last file listed once more without duration
            f.write(f"file '{frames[-1]}'\n")

        raw_h264 = tmp / "test_video.h264"

        cmd = [
            "ffmpeg", "-y",
            "-f", "concat", "-safe", "0",
            "-i", str(concat_txt),
            "-vf", f"scale={WIDTH}:{HEIGHT}",
            "-c:v", "libx264",
            "-profile:v", "baseline",
            "-level", "3.0",
            "-pix_fmt", "yuv420p",
            "-g", str(len(frames)),     # GOP = one full rotation (keyframe per loop)
            "-b:v", "500k",
            "-an",                       # no audio
            str(raw_h264),
        ]
        print("Running:", " ".join(cmd))
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print("ffmpeg stderr:", result.stderr, file=sys.stderr)
            sys.exit(1)

        data = raw_h264.read_bytes()

    total_frames = len(frames) * LOOPS
    print(f"Encoded {total_frames} frames → {len(data)} bytes "
          f"({len(data)/total_frames:.0f} B/frame avg)")

    # Write C header
    lines = [
        "// Auto-generated by scripts/gen_test_video.py — do not edit.",
        "// H.264 Baseline, Annex-B byte stream, 240x240 @ 24 fps.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        f"static constexpr uint16_t TEST_VIDEO_WIDTH  = {WIDTH};",
        f"static constexpr uint16_t TEST_VIDEO_HEIGHT = {HEIGHT};",
        f"static constexpr uint8_t  TEST_VIDEO_FPS    = {FPS};",
        f"static constexpr size_t   TEST_VIDEO_SIZE   = {len(data)};",
        "",
        f"static const uint8_t TEST_VIDEO_DATA[{len(data)}] = {{",
    ]

    # Emit bytes in rows of 16
    hex_bytes = [f"0x{b:02x}" for b in data]
    for i in range(0, len(hex_bytes), 16):
        row = hex_bytes[i:i+16]
        lines.append("    " + ", ".join(row) + ",")

    lines += ["};", ""]

    OUTPUT_H.write_text("\n".join(lines))
    print(f"Written {OUTPUT_H}  ({OUTPUT_H.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
