name=esp_h264
version=1.0.0
author=Espressif Systems
maintainer=Espressif Systems
sentence=espressif/esp-h264-component SW decoder for ESP32-S3 (decoder-only subset)
paragraph=Software H.264 decoder using tinyh264 (h264bsd). ESP32-S3 only.
category=Signal Input/Output
url=https://github.com/espressif/esp-h264-component
architectures=esp32
